gospeltribes-webservice/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', controllers: { sessions: "users_devise/sessions", passwords: "users_devise/passwords" }
  
  devise_scope :user do
    root 'users_devise/sessions#new'
    get 'forgot_password' => "api/v1/sessions#forgot_password"
  end

  # namespace :marketing, path: '' do
  get 'marketing' => 'marketing#index'
  # end

  namespace :admin, path: '' do
    
    get 'admin/profile' => 'dashboard#admin_profile'
    get 'admin/profile_settings' => 'dashboard#admin_profile_settings'
    get 'admin/inbox' => 'dashboard#inbox'
    get 'admin/prayers' => 'dashboard#prayers'
    get 'admin/create_new_admin' => 'dashboard#create_new_admin'

    post 'ajax_delete_messaging' => 'dashboard#ajax_delete_messaging'
    post 'ajax_messaging' => 'dashboard#ajax_messaging'
    post 'edit_personal_info' => 'dashboard#edit_personal_info'
    post 'edit_user_avatar' => 'dashboard#edit_user_avatar'
    post 'edit_user_account' => 'dashboard#edit_user_account'
    post 'create_admin' => 'dashboard#create_admin'
    get 'join_group' => 'dashboard#join_group'
    get 'destroy_from_profile' => 'dashboard#destroy_from_profile'
    post 'create_group' => 'dashboard#create_group'
    post 'create_prayer' => 'prayers#create_to_all'
    get 'delete_prayer' => 'prayers#destroy_all'
    post 'edit_prayer' => 'prayers#edit_all'


    resources :dashboard, path: 'admin', only: [:index, :inbox, :prayers] do
      get 'inbox' => 'pages#index'
      get 'prayers' => 'pages#prayers'
      get 'events' => 'pages#events'
      get 'media' => 'pages#media'
      get 'members' => 'pages#members'
      get 'settings' => 'pages#settings'
      get 'profile' => 'pages#profile'
      get 'profile_settings' => 'pages#profile_settings'
      post 'edit_personal_info' => 'pages#edit_personal_info'
      post 'edit_user_avatar' => 'pages#edit_user_avatar'
      post 'edit_user_account' => 'pages#edit_user_account'
      post 'manage_group' => 'pages#manage_group'
      post 'manage_privilege' => 'pages#manage_privilege'
      post 'ajax_add_event' => 'pages#ajax_add_event'
      post 'ajax_get_groups' => 'pages#ajax_get_groups'
      post 'ajax_messaging' => 'pages#ajax_messaging'
      post 'ajax_delete_messaging' => 'pages#ajax_delete_messaging'
      post 'ajax_delete_media' => 'pages#ajax_delete_media'
      post 'ajax_delete_media_from_profile' => 'pages#ajax_delete_media_from_profile'
      
      get 'sample_page_for_testing' => 'pages#sample_page_for_testing'
      post 'ajax_for_sample_page' => 'pages#ajax_for_sample_page'

      post 'manage_event' => 'events#manage_event'

      get 'member_destroy' => 'members#destroy'
      # resources :prayers, only: [:destroy]
      get 'destroy_prayer' => 'pages#destroy_prayer'
      get 'destroy_from_profile' => 'pages#destroy_from_profile'
      post 'create_prayer' => 'prayers#create'
      post 'edit_prayer' => 'prayers#edit'
    end
  end

  #API
  namespace :api do
    scope :v1, path: '' do
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
        token_validations:  'api/v1/sessions',
        sessions: 'api/v1/sessions',
        registrations: 'api/v1/registrations'
      }
    end
  end

  namespace :api do
  	namespace :v1, path: '' do
  		resources :group, only: [:member_list] do
        get 'group_members' => 'groups#member_list'
      end
      get 'check_group' => 'groups#check_group'
      get 'get_chatrooms' => 'groups#get_chatrooms'
      get 'group_medium' => 'groups#group_medium'
      post 'study_module' => 'groups#study_module'
      post 'edit_study_module' => 'groups#edit_study_module'

      get 'get_study_module' => 'groups#get_study_module'
      get 'delete_study_module' => 'groups#delete_study_module'
      
      post 'add_study_module_comment' => 'groups#add_study_module_comment'
      get 'get_study_module_comment' => 'groups#get_study_module_comment'
      get 'remove_message' => 'groups#remove_message'
      post 'edit_message' => 'groups#edit_message'
      get 'add_group' => 'groups#add_group'
      post 'add_group_image' => 'groups#add_group_image'
      get 'rename_group' => 'groups#rename_group'
      post 'change_chatroom_details' => 'groups#change_chatroom_details'
      get 'remove_group_image' => 'groups#remove_group_image'
      get 'delete_study_module_comment' => 'groups#delete_study_module_comment'
      post 'example_method' => 'groups#example_method'
      get 'set_unread_badges' => 'users#set_unread_badges'
      get 'get_unread_badges' => 'users#get_unread_badges'
      get 'set_read_badges' => 'users#set_read_badges'
      get 'get_sample' => 'users#get_sample'
      
      post 'send_message' => 'messages#send_message'
      get 'get_message' => 'messages#get_message'
      get 'set_read' => 'messages#set_read'
      get 'like_message' => 'messages#like_message'
      get 'unlike_message' => 'messages#unlike_message'
      
      post 'update_user_notification_settings' => 'users#update_user_notification_settings'
      post 'update_account' => 'users#update_account'
      post 'reset_password' => 'users#reset_password'
      get 'retrieve_username' => 'users#retrieve_username'

      get 'user_images' => 'users#user_images'
      get 'update_udid' => 'users#update_udid'
      post 'upload_user_avatar' => 'users#upload_user_avatar'
      get 'get_user_info' => 'users#get_user_info'
      get 'remove_profile' => 'users#remove_profile'
      
      post 'update_profile' => 'users#update_profile'
      post 'create_prayer' => 'prayers#create'
      get 'prayers' => 'prayers#index'
      post 'update_prayer' => 'prayers#update'
      get 'answered_prayers' => 'prayers#answered_prayers'
      get 'unanswered_prayers' => 'prayers#unanswered_prayers'
      get 'prayer_comments' => 'prayers#prayer_comments'
      post 'add_prayer_comment' => 'prayers#add_prayer_comment'
      get 'hide_prayer' => 'prayers#hide_prayer'
      get 'get_all_prayers'=>'prayers#get_all_prayers'
      get 'delete_prayer' => 'prayers#delete_prayer'
      get 'delete_prayer_comment' => 'prayers#delete_prayer_comment'
      
      get 'get_event' => 'events#get_event'
      post 'add_event' => 'events#create'
      get 'all_events' => 'events#index'
      post 'update_event' => 'events#update'
      get 'add_attendee' => 'events#add_attendee'
      get 'attendees' => 'events#get_attendees'
      get 'remove_attendee' => 'events#remove_attendee'
      get 'remove_event' => 'events#remove_event'
  	end
  end
end

gospeltribes-webservice/app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
	before_action :web_authenticate_user!, except: [:ajax_messaging, :ajax_delete_messaging]
	layout 'admin_dashboard'
	def index

		group_creators = GroupCreator.includes(group: [:group_members, :events, :group_medium]).where(user_id: current_user.id)
		@groups = []
		group_creators.each do |gc|
			group = gc.group
			if !group.nil?
				dateTime = DateTime.now
				
				query = "group_id = #{group.id} AND (DATE(start_date) >= '#{dateTime.strftime("%Y-%m-%d")}' OR repeat != 'None')"
    			events_count = group.events.where(query).count


				is_joined = group.group_members.where(user_id: current_user.id).count == 0 ? false : true

				datas = { id: group.id, group_code: group.group_code, group_name: group.group_name, group_image: group.group_image.thumb_160x160, member_count: group.group_members.count, events_count: events_count, media_count: group.group_medium.count, is_joined: is_joined }
				if !@groups.include?(datas)
					@groups.push(datas)
				end
			end
		end
	end

	def prayers
		@prs = []
		prs_ids = []
		@temp = []

		prs = Prayer.includes(:group, user: :group_members).where("from_admin = true AND counter != 0").order('id ASC')
		prs.each do |pr|
			if pr.counter == 1
				if @temp.count != 0
					prs_ids.push(@temp)
					@temp = []
				end
				@prs.push(pr)
				@temp.push(pr.id)
			else
				@temp.push(pr.id)
			end
			
		end
		prs_ids.push(@temp)

		@data = { prs: @prs.reverse!, prs_ids: prs_ids.reverse! }
	end

	def destroy_from_profile
	    @prayer = Prayer.find params[:prayer_id].to_i
	    @prayer.destroy!

	    flash[:notice] = "Prayer removed."
	    redirect_to admin_admin_profile_path
	rescue Exception => e
	    flash[:error] = "Could not delete prayer."
	end

	def inbox
		women_only = []
		women_only_ids = []
		
		men_only = []
		men_only_ids = []
		
		group_text = []
		group_text_ids = []
		
		@chat_messages = []

		last_chat_type = 0
		@temp = []

		cms = ChatroomMessage.includes(:chatroom).where("from_admin = true AND counter != 0")
		cms.each do |cm|
			if !cm.nil?
				case cm.chatroom.chatroom_type
				when 1
					if cm.counter == 1
						if @temp.count != 0
							case last_chat_type
							when 1
								women_only_ids.push(@temp)
							when 2
								men_only_ids.push(@temp)
							when 3
								group_text_ids.push(@temp)
							end
							@temp = []
						end
						last_chat_type = 1
						women_only.push(cm)
						@temp.push(cm.id)
					else
						@temp.push(cm.id)
					end
				when 2
					if(cm.counter == 1)
						if @temp.count != 0
							case last_chat_type
							when 1
								women_only_ids.push(@temp)
							when 2
								men_only_ids.push(@temp)
							when 3
								group_text_ids.push(@temp)
							end
							@temp = []
						end
						last_chat_type = 2
						men_only.push(cm)
						@temp.push(cm.id)
					else
						@temp.push(cm.id)
					end
				when 3
					if(cm.counter == 1)
						if @temp.count != 0
							case last_chat_type
							when 1
								women_only_ids.push(@temp)
							when 2
								men_only_ids.push(@temp)
							when 3
								group_text_ids.push(@temp)
							end
							@temp = []
						end
						last_chat_type = 3
						group_text.push(cm)
						@temp.push(cm.id)
					else
						@temp.push(cm.id)
					end
				end

				
			end
		end
		case last_chat_type
		when 1
			women_only_ids.push(@temp)
		when 2
			men_only_ids.push(@temp)
		when 3
			group_text_ids.push(@temp)
		end

		@chat_messages = { women_only: women_only, men_only: men_only, group_text: group_text, women_only_ids: women_only_ids, men_only_ids: men_only_ids, group_text_ids: group_text_ids }
	end

	def ajax_messaging
		chatrooms = Chatroom.where(chatroom_type: params[:chatroom_type])
		@first_message = nil
		@user = nil
		
		count = 1
		@ids = []
		chatrooms.each do |chatroom|
			message = chatroom.chatroom_messages.includes(:user).create(user_id: params[:user_id], body: params[:body], from_admin: true, counter: count)
			message.save!
			@ids.push(message.id)
			user = message.user
			if(count == 1)
				@first_message = message
				@user = message.user
			end
			
			dateTime = "#{time_ago_in_words(message.created_at)} ago"

		    @data = { action: "send_message", data: { id: message.id, chatroom_type: params[:chatroom_type], user: { id: user.id, first_name: user.first_name, last_name: user.last_name, avatar: { url: user.avatar.url }, username: user.username }, message: message.body, media: nil, date_sent: dateTime } }
	    	broadcast("/group/#{chatroom[:group_id]}/chatrooms/#{chatroom.id}", @data)
	    	broadcast("/group/#{chatroom[:group_id]}/chatrooms", @data)
	    	
	    	ct = params[:chatroom_type].to_i == 1 ? "Female" : (params[:chatroom_type].to_i == 2 ? "Male" : "All")
			topics = "'group_#{chatroom[:group_id].to_i}_iOS_#{ct}' in topics,'group_#{chatroom[:group_id].to_i}_Android_#{ct}' in topics"
			send_to_topic(topics, { action: "message" }, "#{user.first_name.nil? ? user.username : user.first_name} has sent a message", chatroom[:group_id].to_i, ["'group_#{chatroom[:group_id].to_i}_#{user.id}' in topics"], "inbox")
	    	
	    	count += 1
		end

		message = @first_message
	    user = @user
	    dateTime = "#{time_ago_in_words(message.created_at)} ago"
	    @data = { action: "send_message", data: { id: message.id, user: { id: user.id, first_name: user.first_name, last_name: user.last_name, avatar: { url: user.avatar.url }, username: user.username }, message: message.body, media: nil, date_sent: dateTime }, ids: @ids.join(',') }
		render json: @data
	end

	def ajax_delete_messaging
		render json: ChatroomMessage.where("id IN (#{params[:chatroom_message_id]})").destroy_all
	end

	def admin_profile
		@prayers = current_user.prayers.where(is_hidden: false).order("id DESC")
		@media = []

		group_media = GroupMedium.includes(:group).where("user_id=#{current_user.id}").order("id DESC")
		group_media.each do |group_medium|
			group = group_medium.group
			if !group.nil?
				@media.push({ id: group_medium.id, image: group_medium.image.url, group_name: group.group_name, group_code: group.group_code })
			end
		end
	end

	def admin_profile_settings
		
	end

	def edit_personal_info
		current_user.update_attributes(user_params)
		flash[:notice] = "User info updated"
		redirect_to admin_admin_profile_settings_path
	end

	def edit_user_avatar
		current_user.update_attributes(user_params)
		flash[:notice] = "Avatar updated"
		redirect_to admin_admin_profile_settings_path
	end

	def edit_user_account
		if current_user.update_with_password(pass_params)
			bypass_sign_in current_user
			flash[:notice] = "Password successfully updated"
		else
			flash[:error] = "Password not saved"
		end

		redirect_to admin_admin_profile_settings_path
	end

	def create_new_admin
		
	end

	def create_admin
		@user = User.find_by(username: params[:user][:username])
	    if @user.nil?
	    	@user = User.find_by(email: params[:user][:email])
	    	if @user.nil?
	    		if(params[:user][:password].to_s.length < 8)
					flash[:error] = "Password must be 8 characters."
					redirect_to admin_admin_create_new_admin_path
	    		else
	    			group = Group.find 1
					if group.nil?
						flash[:error] = "Group does not exist."
						redirect_to admin_admin_create_new_admin_path
					else
						user = User.create(email: params[:user][:email], password: params[:user][:password], username: params[:user][:username], role: 1)

						group_member = group.group_members.create(user_id: user.id, role: 1)
						if user.save!
							user.settings.create(group_id: group.id, user_id: user.id)               
							flash[:notice] = "Admin created."
							redirect_to admin_admin_create_new_admin_path
						else
							flash[:error] = "Account not created."
							redirect_to admin_admin_create_new_admin_path
						end
					end
	    		end
		    else
				flash[:error] = "Email already exist."
				redirect_to admin_admin_create_new_admin_path
		    end
		    	
	    else
			flash[:error] = "Username already exist."
			redirect_to admin_admin_create_new_admin_path
	    end
	end

	def join_group
		
		g = GroupMember.create(group_id: params[:group_id], user_id: current_user.id, role: 0)
		g.save!
		flash[:notice] = "You have joined the group."
		redirect_to admin_dashboard_index_path
	end

	def create_group
		g = Group.create(group_name: params[:group][:group_name])
		g.save!
		g.group_creators.create(user_id: current_user.id)
		g.save!

		flash[:notice] = "Group successfully created"
		redirect_to admin_dashboard_index_path
	end

	private
		def admin_params
			params.require(:user).permit(:email, :username, :role, :password)
		end
		def user_params
			params.require(:user).permit(:first_name, :last_name, :city, :state, :zip, :phone_number, :birth_date, :email, :gender, :username, :avatar)
		end
		def pass_params
		  	params.require(:pass).permit(:current_password, :password, :password_confirmation, :username)
		  end
end

gospeltribes-webservice/app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

gospeltribes-webservice/app/views/admin/dashboard/admin_profile_settings.html.erb
<style type="text/css">
    .tabbable-line > .nav-tabs > li.active {
        border-bottom: 4px solid #00feff;
    }

    .tabbable-line > .nav-tabs > li.open, .tabbable-line > .nav-tabs > li:hover {
        border-bottom: 4px solid rgba(0, 254, 255, 0.5);
    }

    .font-blue-madison {
        color: #00feff !important;
    }

    .profile-usertitle-job {
        color: #00feff;
    }

    .profile-usermenu ul li.active a {
        color: #00feff;
        border-left: 2px solid #00feff;
    }

    .profile-usertitle-name {
        color: black;
    }

    .btn.green:not(.btn-outline) {
        background-color: #00feff;
        border-color: #00feff;
    }
    
    .profile-usermenu ul li a:hover {
        color: rgba(0, 254, 255, 0.5);
    }
</style>
<div class="row">
    <div class="col-md-12">
        <div class="profile-sidebar">
            <div class="portlet light profile-sidebar-portlet ">
                <div class="profile-userpic">
                    <img src="<%= current_user.avatar.url.nil? ? "../../assets/img/placeholder.png" : current_user.avatar.url %>" class="img-responsive" alt="" style="width: 150px; height: 150px; border: 1px solid black; object-fit: cover;"> </div>
                <div class="profile-usertitle">
                    <div class="profile-usertitle-name"> <%= "#{current_user.first_name} #{current_user.last_name}" %> </div>
                    <div class="profile-usertitle-job"> <%= current_user.username %> </div>

                </div>
                <div class="profile-usermenu">
                    <ul class="nav">
                        <li>
                            <%= link_to admin_admin_profile_path do%>
                                <i class="icon-home"></i> Profile 
                            <%end%>
                        </li>
                        <li class="active">
                            <%= link_to admin_admin_profile_settings_path do %>
                                <i class="icon-settings"></i> Account Settings 
                            <%end%>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="profile-content">
            <div class="row">
                
                <div class="col-md-12">
                    <div class="portlet light ">
                        <div class="portlet-title tabbable-line">
                            <div class="caption caption-md">
                                <i class="icon-globe theme-font hide"></i>
                                <span class="caption-subject font-blue-madison bold uppercase">Profile Account</span>
                            </div>
                            <ul class="nav nav-tabs">
                                <li class="active">
                                    <a href="#tab_1_1" data-toggle="tab">Personal Info</a>
                                </li>
                                <li>
                                    <a href="#tab_1_2" data-toggle="tab">Change Avatar</a>
                                </li>
                                <li>
                                    <a href="#tab_1_3" data-toggle="tab">Account</a>
                                </li>
                            </ul>
                        </div>
                        <div class="portlet-body">
                            <div class="tab-content">
                                <div class="tab-pane active" id="tab_1_1">
                                    <%= form_for User.new, as: :user, url: admin_edit_personal_info_path, role: :form do |f| %>
                                        <div class="form-group">
                                            <%= f.label "First Name", class: "control-label" %>
                                            <%= f.text_field :first_name, placeholder: "First Name", class: "form-control", value: current_user.first_name %>
                                        </div>
                                        <div class="form-group">
                                            <%= f.label "Last Name", class: "control-label" %>
                                            <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control", value: current_user.last_name %>
                                        </div>
                                        <div class="form-group">
                                            <%= f.label "City", class: "control-label" %>
                                            <%= f.text_field :city, placeholder: "City", class: "form-control", value: current_user.city %>
                                        </div>
                                        <div class="form-group">
                                            <%= f.label "State", class: "control-label" %>
                                            <%= f.text_field :state, placeholder: "State", class: "form-control", value: current_user.state %>
                                        </div>
                                        <div class="form-group">
                                            <%= f.label "ZIP", class: "control-label" %>
                                            <%= f.text_field :zip, placeholder: "ZIP", class: "form-control", value: current_user.zip %>
                                        </div>
                                        <div class="form-group">
                                            <%= f.label "Mobile Number", class: "control-label" %>
                                            <%= f.text_field :phone_number, placeholder: "Mobile Number", class: "form-control", value: current_user.phone_number %>
                                        </div>
                                        <div class="form-group">
                                            <%= f.label "Birth Date", class: "control-label" %>
                                            <%= f.text_field :birth_date, placeholder: "Birth Date", class: "form-control", value: current_user.birth_date %>
                                        </div>
                                        <div class="form-group">
                                            <%= f.label "Email", class: "control-label" %>
                                            <%= f.email_field :email, placeholder: "Email", class: "form-control", value: current_user.email %>
                                        </div>
                                        <div class="form-group">
                                            <%= f.label "Gender", class: "control-label" %>
                                            <div class="mt-radio-inline" style="margin-top: -10px;">
                                                <label class="mt-radio">
                                                    <input type="radio" name="user[gender]" value="Male" <%= current_user.gender == "Male" ? "checked" : "" %> /> Male
                                                    <span></span>
                                                </label>
                                                <label class="mt-radio">
                                                    <input type="radio" name="user[gender]" value="Female" <%= current_user.gender == "Female" ? "checked" : "" %> /> Female
                                                    <span></span>
                                                </label>
                                            </div>
                                        </div>
                                        <div class="margiv-top-10">
                                            <%= f.submit "Save Changes", class: "btn green" %>
                                            <!-- <a href="javascript:;" class="btn default"> Cancel </a> -->
                                        </div>
                                    <%end%>
                                </div>
                                <div class="tab-pane" id="tab_1_2">
                                    <%= form_for User.new, as: :user, url: admin_edit_user_avatar_path, role: :form do |f| %>
                                        <div class="form-group">
                                            <div class="fileinput fileinput-new" data-provides="fileinput">
                                                <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                                    <img src="<%= current_user.avatar.url %>" alt="" /> </div>
                                                <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"> </div>
                                                <div>
                                                    <span class="btn default btn-file">
                                                        <span class="fileinput-new"> Select image </span>
                                                        <span class="fileinput-exists"> Change </span>
                                                        <%= f.file_field :avatar %> </span>
                                                    <a href="javascript:;" class="btn default fileinput-exists" data-dismiss="fileinput"> Remove </a>
                                                </div>
                                            </div>
                                        </div>
                                        
                                        <div class="margin-top-10">
                                            <%= f.submit "Submit", class: "btn green" %>
                                        </div>
                                    <%end%>
                                </div>
                                <div class="tab-pane" id="tab_1_3">
                                    <%= form_for User.new, as: :pass, url: admin_edit_user_account_path, role: :form do |f| %>
                                        <div class="form-group">
                                            <%= f.label "Username", class: "control-label" %>
                                            <%= f.text_field :username, placeholder: "Username", class: "form-control", value: current_user.username %>
                                        </div>

                                        <div class="form-group">
                                            <%= f.label "Current Password", class: "control-label" %>
                                            <%= f.password_field :current_password, placeholder: "Current Password", class: "form-control" %>
                                        </div>

                                        <div class="form-group">
                                            <%= f.label "New Password", class: "control-label" %>
                                            <%= f.password_field :password, placeholder: "New Password", class: "form-control" %>
                                        </div>
                                        <div class="form-group">
                                            <%= f.label "Re-type New Password", class: "control-label" %>
                                            <%= f.password_field :password_confirmation, placeholder: "Re-type New Password", class: "form-control" %>
                                        </div>

                                        <div class="margin-top-10">
                                            <%= f.submit "Change Password", class: "btn green" %>
                                        </div>
                                    <%end%>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

gospeltribes-webservice/app/views/admin/dashboard/create_new_admin.html.erb
<% if !flash[:error].nil? %>
    <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
        <strong>Warning!</strong> <%= flash[:error]%>
    </div>
<%end%>

<% if !flash[:notice].nil? %>
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
        <strong>Success!</strong> <%= flash[:notice]%>
    </div>
<%end%>

<%= form_for User.new, as: :user, url: admin_create_admin_path, role: :form do |f| %>
    <%= f.hidden_field :role, value: 1 %>
    <div class="modal-body" style="margin-top: 25px;">
        <div class="form-group">
            <%= f.label "Email", class: "control-label" %>
            <%= f.email_field :email, placeholder: "Email", class: "form-control event_title", required: true %>
        </div>
        <div class="form-group">
            <%= f.label "Username", class: "control-label" %>
            <%= f.text_field :username, placeholder: "Username", class: "form-control event_title", required: true %>
        </div>
        <div class="form-group">
            <%= f.label "Password", class: "control-label" %>
            <%= f.password_field :password, placeholder: "Password", class: "form-control event_title", required: true %>
        </div>
    </div>
    <div class="modal-footer">
        <%= f.submit "Save", class: "btn green save-item" %>
    </div>
<%end%>