gospeltribes-webservice/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', controllers: { sessions: "users_devise/sessions", passwords: "users_devise/passwords" }
  
  devise_scope :user do
    root 'users_devise/sessions#new'
    get 'forgot_password' => "api/v1/sessions#forgot_password"
  end

  # namespace :marketing, path: '' do
  get 'marketing' => 'marketing#index'
  # end

  namespace :admin, path: '' do
    
    get 'admin/profile' => 'dashboard#admin_profile'
    get 'admin/profile_settings' => 'dashboard#admin_profile_settings'
    get 'admin/inbox' => 'dashboard#inbox'
    get 'admin/prayers' => 'dashboard#prayers'
    get 'admin/create_new_admin' => 'dashboard#create_new_admin'

    post 'ajax_delete_messaging' => 'dashboard#ajax_delete_messaging'
    post 'ajax_messaging' => 'dashboard#ajax_messaging'
    post 'edit_personal_info' => 'dashboard#edit_personal_info'
    post 'edit_user_avatar' => 'dashboard#edit_user_avatar'
    post 'edit_user_account' => 'dashboard#edit_user_account'
    post 'create_admin' => 'dashboard#create_admin'
    get 'join_group' => 'dashboard#join_group'
    get 'destroy_from_profile' => 'dashboard#destroy_from_profile'
    post 'create_group' => 'dashboard#create_group'
    post 'create_prayer' => 'prayers#create_to_all'
    get 'delete_prayer' => 'prayers#destroy_all'
    post 'edit_prayer' => 'prayers#edit_all'


    resources :dashboard, path: 'admin', only: [:index, :inbox, :prayers] do
      get 'inbox' => 'pages#index'
      get 'prayers' => 'pages#prayers'
      get 'events' => 'pages#events'
      get 'media' => 'pages#media'
      get 'members' => 'pages#members'
      get 'settings' => 'pages#settings'
      get 'profile' => 'pages#profile'
      get 'profile_settings' => 'pages#profile_settings'
      post 'edit_personal_info' => 'pages#edit_personal_info'
      post 'edit_user_avatar' => 'pages#edit_user_avatar'
      post 'edit_user_account' => 'pages#edit_user_account'
      post 'manage_group' => 'pages#manage_group'
      post 'manage_privilege' => 'pages#manage_privilege'
      post 'ajax_add_event' => 'pages#ajax_add_event'
      post 'ajax_get_groups' => 'pages#ajax_get_groups'
      post 'ajax_messaging' => 'pages#ajax_messaging'
      post 'ajax_delete_messaging' => 'pages#ajax_delete_messaging'
      post 'ajax_delete_media' => 'pages#ajax_delete_media'
      post 'ajax_delete_media_from_profile' => 'pages#ajax_delete_media_from_profile'
      
      get 'sample_page_for_testing' => 'pages#sample_page_for_testing'
      post 'ajax_for_sample_page' => 'pages#ajax_for_sample_page'

      post 'manage_event' => 'events#manage_event'

      get 'member_destroy' => 'members#destroy'
      # resources :prayers, only: [:destroy]
      get 'destroy_prayer' => 'pages#destroy_prayer'
      get 'destroy_from_profile' => 'pages#destroy_from_profile'
      post 'create_prayer' => 'prayers#create'
      post 'edit_prayer' => 'prayers#edit'
    end
  end

  #API
  namespace :api do
    scope :v1, path: '' do
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
        token_validations:  'api/v1/sessions',
        sessions: 'api/v1/sessions',
        registrations: 'api/v1/registrations'
      }
    end
  end

  namespace :api do
  	namespace :v1, path: '' do
  		resources :group, only: [:member_list] do
        get 'group_members' => 'groups#member_list'
      end
      get 'check_group' => 'groups#check_group'
      get 'get_chatrooms' => 'groups#get_chatrooms'
      get 'group_medium' => 'groups#group_medium'
      post 'study_module' => 'groups#study_module'
      post 'edit_study_module' => 'groups#edit_study_module'

      get 'get_study_module' => 'groups#get_study_module'
      get 'delete_study_module' => 'groups#delete_study_module'
      
      post 'add_study_module_comment' => 'groups#add_study_module_comment'
      get 'get_study_module_comment' => 'groups#get_study_module_comment'
      get 'remove_message' => 'groups#remove_message'
      post 'edit_message' => 'groups#edit_message'
      get 'add_group' => 'groups#add_group'
      post 'add_group_image' => 'groups#add_group_image'
      get 'rename_group' => 'groups#rename_group'
      post 'change_chatroom_details' => 'groups#change_chatroom_details'
      get 'remove_group_image' => 'groups#remove_group_image'
      get 'delete_study_module_comment' => 'groups#delete_study_module_comment'
      post 'example_method' => 'groups#example_method'
      get 'set_unread_badges' => 'users#set_unread_badges'
      get 'get_unread_badges' => 'users#get_unread_badges'
      get 'set_read_badges' => 'users#set_read_badges'
      get 'get_sample' => 'users#get_sample'
      
      post 'send_message' => 'messages#send_message'
      get 'get_message' => 'messages#get_message'
      get 'set_read' => 'messages#set_read'
      get 'like_message' => 'messages#like_message'
      get 'unlike_message' => 'messages#unlike_message'
      
      post 'update_user_notification_settings' => 'users#update_user_notification_settings'
      post 'update_account' => 'users#update_account'
      post 'reset_password' => 'users#reset_password'
      get 'retrieve_username' => 'users#retrieve_username'

      get 'user_images' => 'users#user_images'
      get 'update_udid' => 'users#update_udid'
      post 'upload_user_avatar' => 'users#upload_user_avatar'
      get 'get_user_info' => 'users#get_user_info'
      get 'remove_profile' => 'users#remove_profile'
      
      post 'update_profile' => 'users#update_profile'
      post 'create_prayer' => 'prayers#create'
      get 'prayers' => 'prayers#index'
      post 'update_prayer' => 'prayers#update'
      get 'answered_prayers' => 'prayers#answered_prayers'
      get 'unanswered_prayers' => 'prayers#unanswered_prayers'
      get 'prayer_comments' => 'prayers#prayer_comments'
      post 'add_prayer_comment' => 'prayers#add_prayer_comment'
      get 'hide_prayer' => 'prayers#hide_prayer'
      get 'get_all_prayers'=>'prayers#get_all_prayers'
      get 'delete_prayer' => 'prayers#delete_prayer'
      get 'delete_prayer_comment' => 'prayers#delete_prayer_comment'
      
      get 'get_event' => 'events#get_event'
      post 'add_event' => 'events#create'
      get 'all_events' => 'events#index'
      post 'update_event' => 'events#update'
      get 'add_attendee' => 'events#add_attendee'
      get 'attendees' => 'events#get_attendees'
      get 'remove_attendee' => 'events#remove_attendee'
      get 'remove_event' => 'events#remove_event'
  	end
  end
end

gospeltribes-webservice/app/views/layouts/admin_dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
      <%= csp_meta_tag %>
      <%= csrf_meta_tags %>
      <meta charset="utf-8" />
      <title>Gospel Tribes | Dashboard</title>
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <!-- <meta content="Preview page of Metronic Admin Theme #3 for dashboard & statistics" name="description" /> -->
      <!-- <meta content="" name="author" /> -->
      <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
      <link href="../assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
      <link href="../assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
      <link href="../assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
      <link href="../assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />

      <%if controller.action_name == "prayers"%>
      <link href="../../assets/global/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" type="text/css" />
      <%end%>

      <link href="../../assets/global/plugins/cubeportfolio/css/cubeportfolio.css" rel="stylesheet" type="text/css" />
      <link href="../../assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css" rel="stylesheet" type="text/css" />


      <link href="../assets/global/css/components.min.css" rel="stylesheet" id="style_components" type="text/css" />
      <link href="../assets/global/css/plugins.min.css" rel="stylesheet" type="text/css" />

      <link href="../../assets/pages/css/portfolio.min.css" rel="stylesheet" type="text/css" />
      <link href="../../assets/pages/css/profile.min.css" rel="stylesheet" type="text/css" />

      <link href="../assets/layouts/layout3/css/layout.min.css" rel="stylesheet" type="text/css" />
      <link href="../assets/layouts/layout3/css/themes/default.min.css" rel="stylesheet" type="text/css" id="style_color" />
      <link href="../assets/layouts/layout3/css/custom.min.css" rel="stylesheet" type="text/css" />

      <link rel="shortcut icon" href="../assets/img/MainLogo.png" />
      <style type="text/css">
        .page-header .page-header-top .top-menu .navbar-nav>li.dropdown-dark .dropdown-menu .dropdown-menu-list>li a>i, .page-header .page-header-top .top-menu .navbar-nav>li.dropdown-dark .dropdown-menu.dropdown-menu-default>li a>i {
          color: #00feff;
        }

        .alert-success {
          background-color: #00feff;
          border-color: #00feff;
          color: #ffffff;
        }
      </style>
      
    </head>

    <body class="page-container-bg-solid">
        <% flash.each do |key, value| %>
          <%if key == "notice"%>
            <div class="alert alert-success alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
              <strong>Success!</strong> <%= value %>
            </div>
          <%elsif key == "alert"%>
            <div class="alert alert-warning alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
              <strong>Warning!</strong> <%= value %>
            </div>
          <%end%>
        <%end%>
        <div class="page-wrapper">
            <div class="page-wrapper-row">
                <div class="page-wrapper-top">
                    <div class="page-header" style="height: 63px;">
                        <div class="page-header-top">
                            <div class="container-fluid">
                                <div class="page-logo">
                                    <%= link_to(admin_dashboard_index_path) do%>
                                        <img src="../assets/img/logo-default.png" alt="logo" class="logo-default">
                                    <% end %>
                                </div>
                                <!-- <a href="javascript:;" class="menu-toggler"></a> -->
                                <div class="top-menu">
                                    <ul class="nav navbar-nav pull-right">
                                        <li class="dropdown dropdown-extended dropdown-notification dropdown-dark" id="header_notification_bar">
                                            <%= link_to "Dashboard", admin_dashboard_index_path, class: "dropdown-toggle", style: "color: #{current_page?(controller: :dashboard, action: :index) ? '#00feff' : '#9cabbc'};" %>
                                            <!-- <%= current_page?(controller: :dashboard) %> -->
                                        </li>
                                        <li class="dropdown dropdown-extended dropdown-notification dropdown-dark" id="header_notification_bar">
                                            <%= link_to "Inbox", admin_admin_inbox_path, class: "dropdown-toggle", style: "color: #{current_page?(controller: :dashboard, action: :inbox) ? '#00feff' : '#9cabbc'};" %>
                                            <!-- <%= current_page?(controller: :dashboard) %> -->
                                        </li>
                                        <li class="dropdown dropdown-extended dropdown-notification dropdown-dark" id="header_notification_bar">
                                            <%= link_to "Prayers", admin_admin_prayers_path, class: "dropdown-toggle", style: "color: #{current_page?(controller: :dashboard, action: :prayers) ? '#00feff' : '#9cabbc'};" %>
                                            <!-- <%= current_page?(controller: :dashboard) %> -->
                                        </li>

                                        

                                        <li class="droddown dropdown-separator">
                                            <span class="separator"></span>
                                        </li>

                                        <li class="dropdown dropdown-user dropdown-dark">
                                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                                <img alt="" class="img-circle" src="<%= current_user.avatar.url %>">
                                                <span class="username username-hide-mobile"><%= "#{current_user.first_name} #{current_user.last_name}" %></span>
                                            </a>
                                            <ul class="dropdown-menu dropdown-menu-default">
                                                <!-- <li style="background-color: #eee;"> -->
                                                <li>
                                                    <%= link_to(admin_dashboard_index_path) do %>
                                                        <i class="icon-users"></i> My Groups
                                                    <%end%>
                                                </li>
                                                <li>
                                                    <%= link_to(admin_admin_profile_path) do %>
                                                        <i class="icon-user"></i> My Profile
                                                    <%end%>
                                                </li>
                                                <!-- <li class="divider"> </li> -->
                                                <li>
                                                    <%= link_to destroy_user_session_path do %>
                                                        <i class="icon-key"></i> Log Out
                                                    <%end%>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="page-wrapper-row full-height">
                <div class="page-wrapper-middle">
                    <div class="page-container">
                        <div class="page-content-wrapper">
                            
                            <div class="page-content">
                                <div class="container">
                                    <ul class="page-breadcrumb breadcrumb">
                                        <%if controller.action_name == "index"%>
                                        <li>
                                            <%= link_to "Dashboard",(admin_dashboard_index_path), { style: "color: black;" } %>
                                        </li>
                                        <%end%>
                                        
                                    </ul>
                                    <div class="page-content-inner">
                                        <%= yield %>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
            <div class="page-wrapper-row">
                <div class="page-wrapper-bottom">
                    <div class="page-footer">
                        <div class="container"> 2018 &copy; 
                            <%= link_to "Gospel Tribes", admin_dashboard_index_path %>
                        </div>
                    </div>
                    <div class="scroll-to-top">
                        <i class="icon-arrow-up"></i>
                    </div>
                </div>
            </div>
        </div>

        
        
        <script src="../assets/global/plugins/jquery.min.js" type="text/javascript"></script>
        <script src="../assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="../assets/global/plugins/js.cookie.min.js" type="text/javascript"></script>
        <script src="../assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
        <script src="../assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
        <script src="../assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
        <%if controller.action_name == "prayers"%>
            <script src="../../assets/global/plugins/bootstrap-select/js/bootstrap-select.min.js" type="text/javascript"></script>
        <%end%>



        <script src="../assets/global/plugins/counterup/jquery.waypoints.min.js" type="text/javascript"></script>
        <script src="../assets/global/plugins/counterup/jquery.counterup.min.js" type="text/javascript"></script>
        
        <script src="../../assets/global/plugins/cubeportfolio/js/jquery.cubeportfolio.js" type="text/javascript"></script>
        <script src="../../assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js" type="text/javascript"></script>
        <script src="../../assets/global/plugins/jquery.sparkline.min.js" type="text/javascript"></script>

        <script src="../assets/global/scripts/app.min.js" type="text/javascript"></script>
        
        <%if controller.action_name == "prayers"%>
            <script src="../../assets/pages/scripts/components-bootstrap-select.js" type="text/javascript"></script>
        <%end%>
        
        <script src="../../assets/pages/scripts/portfolio-4.js" type="text/javascript"></script>
        <script src="../assets/pages/scripts/profile.min.js" type="text/javascript"></script>

        <script src="../assets/layouts/layout3/scripts/layout.min.js" type="text/javascript"></script>
        <script src="../assets/layouts/layout3/scripts/demo.min.js" type="text/javascript"></script>
        <script src="../assets/layouts/global/scripts/quick-sidebar.min.js" type="text/javascript"></script>
        <script src="../assets/layouts/global/scripts/quick-nav.min.js" type="text/javascript"></script>
        <%= yield(:important_javascript) %>

    </body>

</html>

gospeltribes-webservice/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
      <%= csp_meta_tag %>
      <%= csrf_meta_tags %>
      <meta charset="utf-8" />
      <title>Gospel Tribes | Dashboard</title>
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
      <link href="<%= controller_name == "passwords" ? "../" : "" %>assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
      <link href="<%= controller_name == "passwords" ? "../" : "" %>assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
      <link href="<%= controller_name == "passwords" ? "../" : "" %>assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
      <link href="<%= controller_name == "passwords" ? "../" : "" %>assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
      <link href="<%= controller_name == "passwords" ? "../" : "" %>assets/global/plugins/select2/css/select2.min.css" rel="stylesheet" type="text/css" />
      <link href="<%= controller_name == "passwords" ? "../" : "" %>assets/global/plugins/select2/css/select2-bootstrap.min.css" rel="stylesheet" type="text/css" />
      <link href="<%= controller_name == "passwords" ? "../" : "" %>assets/global/css/components.min.css" rel="stylesheet" id="style_components" type="text/css" />
      <link href="<%= controller_name == "passwords" ? "../" : "" %>assets/global/css/plugins.min.css" rel="stylesheet" type="text/css" />
      <link href="<%= controller_name == "passwords" ? "../" : "" %>assets/pages/css/login-2.min.css" rel="stylesheet" type="text/css" />

      
      <link rel="shortcut icon" href="<%= controller_name == "passwords" ? "../" : "" %>assets/img/MainLogo.png" />
      <script src="<%= controller_name == "passwords" ? "../" : "" %>assets/global/plugins/jquery.min.js" type="text/javascript"></script>
      <style type="text/css">
        .alert-success {
          background-color: #00feff;
          border-color: #00feff;
          color: #ffffff;
        }
      </style>
    </head>
    <body class="login" style="background-color: #00feff;">
        <% flash.each do |key, value| %>
          <%if key == "notice"%>
            <div class="alert alert-success alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
              <strong>Success!</strong> <%= value %>
            </div>
          <%end%>

          <%if key == "alert"%>
            <div class="alert alert-warning alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
              <strong>Warning!</strong> <%= value %>
            </div>
          <%end%>
        <%end%>
        <%= yield %>
        
      
      <script src="<%= controller_name == "passwords" ? "../" : "" %>assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
      <script src="<%= controller_name == "passwords" ? "../" : "" %>assets/global/plugins/js.cookie.min.js" type="text/javascript"></script>
      <script src="<%= controller_name == "passwords" ? "../" : "" %>assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
      <script src="<%= controller_name == "passwords" ? "../" : "" %>assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
      <script src="<%= controller_name == "passwords" ? "../" : "" %>assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
      <script src="<%= controller_name == "passwords" ? "../" : "" %>assets/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
      <script src="<%= controller_name == "passwords" ? "../" : "" %>assets/global/plugins/jquery-validation/js/additional-methods.min.js" type="text/javascript"></script>
      <script src="<%= controller_name == "passwords" ? "../" : "" %>assets/global/plugins/select2/js/select2.full.min.js" type="text/javascript"></script>
      <script src="<%= controller_name == "passwords" ? "../" : "" %>assets/global/scripts/app.min.js" type="text/javascript"></script>
      <script src="<%= controller_name == "passwords" ? "../" : "" %>assets/pages/scripts/login.min.js" type="text/javascript"></script>
    </body>
</html>