gospeltribes-webservice/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', controllers: { sessions: "users_devise/sessions", passwords: "users_devise/passwords" }
  
  devise_scope :user do
    root 'users_devise/sessions#new'
    get 'forgot_password' => "api/v1/sessions#forgot_password"
  end

  # namespace :marketing, path: '' do
  get 'marketing' => 'marketing#index'
  # end

  namespace :admin, path: '' do
    
    get 'admin/profile' => 'dashboard#admin_profile'
    get 'admin/profile_settings' => 'dashboard#admin_profile_settings'
    get 'admin/inbox' => 'dashboard#inbox'
    get 'admin/prayers' => 'dashboard#prayers'
    get 'admin/create_new_admin' => 'dashboard#create_new_admin'

    post 'ajax_delete_messaging' => 'dashboard#ajax_delete_messaging'
    post 'ajax_messaging' => 'dashboard#ajax_messaging'
    post 'edit_personal_info' => 'dashboard#edit_personal_info'
    post 'edit_user_avatar' => 'dashboard#edit_user_avatar'
    post 'edit_user_account' => 'dashboard#edit_user_account'
    post 'create_admin' => 'dashboard#create_admin'
    get 'join_group' => 'dashboard#join_group'
    get 'destroy_from_profile' => 'dashboard#destroy_from_profile'
    post 'create_group' => 'dashboard#create_group'
    post 'create_prayer' => 'prayers#create_to_all'
    get 'delete_prayer' => 'prayers#destroy_all'
    post 'edit_prayer' => 'prayers#edit_all'


    resources :dashboard, path: 'admin', only: [:index, :inbox, :prayers] do
      get 'inbox' => 'pages#index'
      get 'prayers' => 'pages#prayers'
      get 'events' => 'pages#events'
      get 'media' => 'pages#media'
      get 'members' => 'pages#members'
      get 'settings' => 'pages#settings'
      get 'profile' => 'pages#profile'
      get 'profile_settings' => 'pages#profile_settings'
      post 'edit_personal_info' => 'pages#edit_personal_info'
      post 'edit_user_avatar' => 'pages#edit_user_avatar'
      post 'edit_user_account' => 'pages#edit_user_account'
      post 'manage_group' => 'pages#manage_group'
      post 'manage_privilege' => 'pages#manage_privilege'
      post 'ajax_add_event' => 'pages#ajax_add_event'
      post 'ajax_get_groups' => 'pages#ajax_get_groups'
      post 'ajax_messaging' => 'pages#ajax_messaging'
      post 'ajax_delete_messaging' => 'pages#ajax_delete_messaging'
      post 'ajax_delete_media' => 'pages#ajax_delete_media'
      post 'ajax_delete_media_from_profile' => 'pages#ajax_delete_media_from_profile'
      
      get 'sample_page_for_testing' => 'pages#sample_page_for_testing'
      post 'ajax_for_sample_page' => 'pages#ajax_for_sample_page'

      post 'manage_event' => 'events#manage_event'

      get 'member_destroy' => 'members#destroy'
      # resources :prayers, only: [:destroy]
      get 'destroy_prayer' => 'pages#destroy_prayer'
      get 'destroy_from_profile' => 'pages#destroy_from_profile'
      post 'create_prayer' => 'prayers#create'
      post 'edit_prayer' => 'prayers#edit'
    end
  end

  #API
  namespace :api do
    scope :v1, path: '' do
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
        token_validations:  'api/v1/sessions',
        sessions: 'api/v1/sessions',
        registrations: 'api/v1/registrations'
      }
    end
  end

  namespace :api do
  	namespace :v1, path: '' do
  		resources :group, only: [:member_list] do
        get 'group_members' => 'groups#member_list'
      end
      get 'check_group' => 'groups#check_group'
      get 'get_chatrooms' => 'groups#get_chatrooms'
      get 'group_medium' => 'groups#group_medium'
      post 'study_module' => 'groups#study_module'
      post 'edit_study_module' => 'groups#edit_study_module'

      get 'get_study_module' => 'groups#get_study_module'
      get 'delete_study_module' => 'groups#delete_study_module'
      
      post 'add_study_module_comment' => 'groups#add_study_module_comment'
      get 'get_study_module_comment' => 'groups#get_study_module_comment'
      get 'remove_message' => 'groups#remove_message'
      post 'edit_message' => 'groups#edit_message'
      get 'add_group' => 'groups#add_group'
      post 'add_group_image' => 'groups#add_group_image'
      get 'rename_group' => 'groups#rename_group'
      post 'change_chatroom_details' => 'groups#change_chatroom_details'
      get 'remove_group_image' => 'groups#remove_group_image'
      get 'delete_study_module_comment' => 'groups#delete_study_module_comment'
      post 'example_method' => 'groups#example_method'
      get 'set_unread_badges' => 'users#set_unread_badges'
      get 'get_unread_badges' => 'users#get_unread_badges'
      get 'set_read_badges' => 'users#set_read_badges'
      get 'get_sample' => 'users#get_sample'
      
      post 'send_message' => 'messages#send_message'
      get 'get_message' => 'messages#get_message'
      get 'set_read' => 'messages#set_read'
      get 'like_message' => 'messages#like_message'
      get 'unlike_message' => 'messages#unlike_message'
      
      post 'update_user_notification_settings' => 'users#update_user_notification_settings'
      post 'update_account' => 'users#update_account'
      post 'reset_password' => 'users#reset_password'
      get 'retrieve_username' => 'users#retrieve_username'

      get 'user_images' => 'users#user_images'
      get 'update_udid' => 'users#update_udid'
      post 'upload_user_avatar' => 'users#upload_user_avatar'
      get 'get_user_info' => 'users#get_user_info'
      get 'remove_profile' => 'users#remove_profile'
      
      post 'update_profile' => 'users#update_profile'
      post 'create_prayer' => 'prayers#create'
      get 'prayers' => 'prayers#index'
      post 'update_prayer' => 'prayers#update'
      get 'answered_prayers' => 'prayers#answered_prayers'
      get 'unanswered_prayers' => 'prayers#unanswered_prayers'
      get 'prayer_comments' => 'prayers#prayer_comments'
      post 'add_prayer_comment' => 'prayers#add_prayer_comment'
      get 'hide_prayer' => 'prayers#hide_prayer'
      get 'get_all_prayers'=>'prayers#get_all_prayers'
      get 'delete_prayer' => 'prayers#delete_prayer'
      get 'delete_prayer_comment' => 'prayers#delete_prayer_comment'
      
      get 'get_event' => 'events#get_event'
      post 'add_event' => 'events#create'
      get 'all_events' => 'events#index'
      post 'update_event' => 'events#update'
      get 'add_attendee' => 'events#add_attendee'
      get 'attendees' => 'events#get_attendees'
      get 'remove_attendee' => 'events#remove_attendee'
      get 'remove_event' => 'events#remove_event'
  	end
  end
end

gospeltribes-webservice/app/views/admin/pages/media.html.erb
<div class="portfolio-content portfolio-4">
    <% if @media.count == 0 %>
        <h3 align="center">EMPTY</h3>
    <% else %>
        <div id="js-grid-full-width" class="cbp">
            <% @media.each do |medium| %>
                <div class="cbp-item" style="border: 0.5px solid #eee;">
                    <a href="<%= medium.is_video ? medium.video_name.thumb.url : medium.image.url %>" class="cbp-caption cbp-lightbox" data-title="by <%= (medium.user.first_name.nil? && medium.user.last_name.nil?) ?  medium.user.username : "#{medium.user.first_name} #{medium.user.last_name}" %>">
                        <div class="cbp-caption-defaultWrap">
                            <img src="<%= medium.is_video ? medium.video_name.thumb.url : medium.image.url %>" alt=""> </div>
                        <div class="cbp-caption-activeWrap">
                            <div class="cbp-l-caption-alignLeft">
                                <div class="cbp-l-caption-body">
                                    <div class="cbp-l-caption-desc">
                                        by <%= (medium.user.first_name.nil? && medium.user.last_name.nil?) ?  medium.user.username : "#{medium.user.first_name} #{medium.user.last_name}" %>
                                        <div class="btn btn-circle red btn-sm div-as-button" style="margin-top: -7px; float: right;" data-id="<%= medium.id %>"><i class="icon-trash"></i> Remove</div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            <% end %>
        </div>
    <% end %>
</div>
<%= content_for(:javascript) do %>
    <script type="text/javascript">
        $(document).ready(function(){

            function constructNewGallery(e){
                var content = "<div id=\"js-grid-full-width\" class=\"cbp\">";
                e.media.forEach(function(element){
                    content += "<div class=\"cbp-item\" style=\"border: 0.5px solid #eee;\">" + 
                        "<a href=\"" + (element["medium"]["is_video"] ? element["medium"]["video_name"]["thumb"]["url"] : element["medium"]["image"]["url"]) + "\" class=\"cbp-caption cbp-lightbox\" data-title=\"by " + ((element["user"]["first_name"] == null && element["user"]["last_name"] == null) ? element["user"]["username"] : element["user"]["first_name"] + " " + element["user"]["last_name"]) + " \">" + 
                            "<div class=\"cbp-caption-defaultWrap\">" + 
                                "<img src=\"" + (element["medium"]["is_video"] ? element["medium"]["video_name"]["thumb"]["url"] : element["medium"]["image"]["url"]) + "\" alt=\"\"> </div>" +
                            "<div class=\"cbp-caption-activeWrap\">" + 
                                "<div class=\"cbp-l-caption-alignLeft\">" + 
                                    "<div class=\"cbp-l-caption-body\">" + 
                                        "<div class=\"cbp-l-caption-desc\">" + 
                                            "by " + ((element["user"]["first_name"] == null && element["user"]["last_name"] == null) ? element["user"]["username"] : element["user"]["first_name"] + " " + element["user"]["last_name"]) + 
                                            "<div class=\"btn btn-circle red btn-sm div-as-button\" style=\"margin-top: -7px; float: right;\" data-id=\"" + element["medium"]["id"] + "\"><i class=\"icon-trash\"></i> Remove</div>" + 
                                        "</div>" + 

                                    "</div>" + 
                                "</div>" + 
                            "</div>" + 
                        "</a>" + 
                    "</div>";
                });
                content += "</div>";
                return content;
            }

            $('.div-as-button').click(buttonCallback);

            function buttonCallback(e){
                if(confirm("Do you really want to delete this image?")){
                    $.ajax({
                        url: "<%= admin_dashboard_ajax_delete_media_path %>",
                        method: "post",
                        data: { media_id: $(this).data("id") },
                        success: function(e){
                            if(e.media.length != 0){
                                $('.portfolio-4').html(constructNewGallery(e));

                                $('#js-grid-full-width').cubeportfolio({
                                    filters: '#js-filters-full-width',
                                    loadMore: '#js-loadMore-full-width',
                                    loadMoreAction: 'auto',
                                    layoutMode: 'mosaic',
                                    sortToPreventGaps: true,
                                    defaultFilter: '*',
                                    animationType: 'fadeOutTop',
                                    gapHorizontal: 0,
                                    gapVertical: 0,
                                    gridAdjustment: 'responsive',
                                    mediaQueries: [{
                                        width: 1500,
                                        cols: 5
                                    }, {
                                        width: 1100,
                                        cols: 4
                                    }, {
                                        width: 800,
                                        cols: 3
                                    }, {
                                        width: 480,
                                        cols: 2
                                    }, {
                                        width: 320,
                                        cols: 1
                                    }],
                                    caption: 'zoom',
                                    displayType: 'lazyLoading',
                                    displayTypeSpeed: 100,
                                    
                                    // lightbox
                                    lightboxDelegate: '.cbp-lightbox',
                                    lightboxGallery: true,
                                    lightboxTitleSrc: 'data-title',
                                    lightboxCounter: '<div class="cbp-popup-lightbox-counter">{{current}} of {{total}}</div>',
                                });
                                $('.div-as-button').click(buttonCallback);
                            }else{
                                $('.cbp').html("<h3 align=\"center\">EMPTY</h3>");
                            }
                            // this_parent.remove();
                        }
                    });
                }
                
                return false;

            }
        });
    </script>
<% end %>

gospeltribes-webservice/app/views/admin/pages/members.html.erb
<style type="text/css">
    .font-green-steel {
        color: #00feff !important;
    }

    .btn.green:not(.btn-outline) {
        background-color: #00feff;
        border-color: #00feff;
    }
</style>
<div class="col-md-12 col-sm-12">
    <div class="portlet light ">
        <div class="portlet-title">
            <div class="caption caption-md">
                <i class="icon-bar-chart font-dark hide"></i>
                <span class="caption-subject font-green-steel bold uppercase">Members</span>
            </div>
        </div>
        <div class="portlet-body">
            <div class="table-scrollable table-scrollable-borderless">
                <table class="table table-hover table-light">
                    <thead>
                        <tr class="uppercase">
                            <th colspan="2"> NAME </th>
                            <th> PRAYERS </th>
                            <th> MEDIA FILES </th>
                            <th> ACTION </th>
                        </tr>
                    </thead>
                    <% @group_members.each do |member| %>
                        <tr>
                            <td class="fit">
                                <img class="user-pic rounded" style="height: 45px; width: 45px; object-fit: cover; border: 1px solid black;" src="<%= member[:avatar].nil? ? "../../../assets/img/placeholder.png" : "../..#{member[:avatar]}" %>"> </td>
                            <td>
                                <a href="javascript:;" class="primary-link"><%= member[:first_name].nil? && member[:last_name].nil? ? member[:username] : "#{member[:first_name]} #{member[:last_name]}" %></a>
                            </td>
                            <td> <%= member[:prayer_count] %> </td>
                            <td> <%= member[:group_medium_count] %> </td>
                            <td class="col-xs-2">
                                <%= link_to admin_dashboard_profile_path(id: member[:id]), class: "btn btn-circle green btn-sm" do %>
                                    <i class="icon-eye"></i> View 
                                <% end %>
                                <%if member[:role].to_i != 1%>
                                    <%= link_to admin_dashboard_member_destroy_path(member), data: {confirm: 'Are you sure you want to delete this member?'}, class: "btn btn-circle red btn-sm" do %>
                                        <i class="icon-trash"></i> Remove 
                                    <% end %>
                                <%end%>

                                <% if member[:id] != current_user.id %>
                                <%= link_to admin_dashboard_profile_settings_path(id: member[:id])+"#tab_1_4", class: "btn btn-circle green btn-sm" do %>
                                    <!-- <i class="icon-eye"></i> --> Privilege 
                                <% end %>
                                <%end%>
                            </td>
                        </tr>
                    <% end %>
                </table>
            </div>
        </div>
    </div>
</div>

gospeltribes-webservice/app/views/admin/pages/profile.html.erb
<style type="text/css">
    .tabbable-line > .nav-tabs > li.active {
        border-bottom: 4px solid #00feff;
    }

    .tabbable-line > .nav-tabs > li.open, .tabbable-line > .nav-tabs > li:hover {
        border-bottom: 4px solid rgba(0, 254, 255, 0.5);
    }

    .mt-comments .mt-comment .mt-comment-body .mt-comment-details .mt-comment-status.mt-comment-status-rejected {
        color: black;
    }

    .font-blue-madison {
        color: #00feff !important;
    }

    .profile-usertitle-job {
        color: #00feff;
    }

    .profile-usermenu ul li.active a {
        color: #00feff;
        border-left: 2px solid #00feff;
    }

    .profile-usertitle-name {
        color: black;
    }

    .profile-usermenu ul li a:hover {
        color: rgba(0, 254, 255, 0.5);
    }
</style>
<div class="row">
    <div class="col-md-12">
        <div class="profile-sidebar">
            <div class="portlet light profile-sidebar-portlet ">
                <div class="profile-userpic">
                    <img src="<%= @user.avatar.url.nil? ? "../../../assets/img/placeholder.png" : @user.avatar.url %>" class="img-responsive" alt="" style="width: 150px; height: 150px; border: 1px solid black; object-fit: cover;"> </div>
                <div class="profile-usertitle">
                    <div class="profile-usertitle-name"> <%= "#{@user.first_name} #{@user.last_name}" %> </div>
                    <div class="profile-usertitle-job"> <%= "#{@user.username}" %> </div>
                </div>
                <div class="profile-usermenu">
                    <ul class="nav">
                        <li class="active">
                            <%= link_to admin_dashboard_profile_path(id: params[:id]) do%>
                            <i class="icon-home"></i> Profile 
                            <%end%>
                        </li>
                        <li>
                            <%= link_to admin_dashboard_profile_settings_path(id: params[:id]) do%>
                            <i class="icon-settings"></i> Account Settings 
                            <%end%>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="profile-content">
            <div class="row">
                
                <div class="col-md-12">
                    <div class="portlet light ">
                        <div class="portlet-title tabbable-line">
                            <div class="caption caption-md">
                                <span class="caption-subject font-blue-madison bold uppercase">Profile</span>
                            </div>
                            <ul class="nav nav-tabs">
                                <li class="active">
                                    <a href="#tab_1_1" data-toggle="tab"> Media </a>
                                </li>
                                <li>
                                    <a href="#tab_1_2" data-toggle="tab"> Prayer </a>
                                </li>
                            </ul>
                        </div>
                        <div class="portlet-body">
                            <div class="tab-content">
                                <div class="tab-pane active" id="tab_1_1">
                                    <% if @prayers.count == 0 %>
                                        <h3 align="center">EMPTY</h3>
                                    <%else%>
                                        <div class="mt-comments">
                                            <% @prayers.each do |prayer| %>
                                                <div class="mt-comment">
                                                    <div class="mt-comment-img">
                                                        <img style="width: 45px; height: 45px; object-fit: cover; border: 1px solid black;" src="<%= @user.avatar.url.nil? ? "../../../assets/img/placeholder.png" : @user.avatar.url %>" /> </div>
                                                    <div class="mt-comment-body">
                                                        <div class="mt-comment-info">
                                                            <span class="mt-comment-author"><%= (@user.first_name.nil? && @user.last_name.nil?) ?  @user.username : "#{@user.first_name} #{@user.last_name}" %></span>
                                                            <span class="mt-comment-date"><%= prayer.created_at %></span>
                                                        </div>
                                                        <div class="mt-comment-text"> <%= prayer.details %> </div>
                                                        <div class="mt-comment-details">
                                                            <span class="mt-comment-status mt-comment-status-rejected"><%= prayer.subject %></span>
                                                            <ul class="mt-comment-actions">
                                                                <%= link_to admin_dashboard_destroy_from_profile_path(prayer_id: prayer.id, user_id: params[:id]), data: {confirm: 'Are you sure you want to delete this prayer?'}, class: "btn btn-circle red btn-sm" do %>
                                                                    <i class="icon-trash"></i> Remove 
                                                                <% end %>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                            <% end %>
                                        </div>
                                    <%end%>
                                </div>
                                <div class="tab-pane" id="tab_1_2">
                                    <% if @media.count == 0 %>
                                        <h3 align="center">EMPTY</h3>
                                    <%else%>
                                        <div class="portfolio-content portfolio-4">
                                            <div id="js-grid-full-width" class="cbp">
                                                <% @media.each do |medium| %>
                                                    <div class="cbp-item" style="border: 0.5px solid #eee;">
                                                        <a href="<%= medium[:is_video] ? medium[:thumb] : medium[:image] %>" class="cbp-caption cbp-lightbox" >
                                                            <div class="cbp-caption-defaultWrap">
                                                                <img src="<%= medium[:is_video] ? medium[:thumb] : medium[:image] %>" alt="">
                                                            </div>
                                                            <div class="cbp-caption-activeWrap">
                                                                <div class="cbp-l-caption-alignLeft">
                                                                    <div class="cbp-l-caption-body">
                                                                        <div class="cbp-l-caption-desc">
                                                                            <div class="btn btn-circle red btn-sm div-as-button" style="margin-top: -7px; float: right;" data-id="<%= medium[:id] %>"><i class="icon-trash"></i> Remove</div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </a>
                                                    </div>
                                                <% end %>
                                            </div>
                                        </div>
                                    <%end%>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<%= content_for(:javascript) do %>
    <script type="text/javascript">
        $(document).ready(function(){
            function constructNewGallery(e){
                var content = "<div id=\"js-grid-full-width\" class=\"cbp\">";
                e.media.forEach(function(element){
                    content += "<div class=\"cbp-item\" style=\"border: 0.5px solid #eee;\">" +
                        "<a href=\" " + (element["is_video"] ? element["thumb"] : element["image"]) + " \" class=\"cbp-caption cbp-lightbox\" >" +
                            "<div class=\"cbp-caption-defaultWrap\">" +
                                "<img src=\" " + (element["is_video"] ? element["thumb"] : element["image"]) + " \" >" +
                            "</div>" +
                            "<div class=\"cbp-caption-activeWrap\">" +
                                "<div class=\"cbp-l-caption-alignLeft\">" +
                                    "<div class=\"cbp-l-caption-body\">" +
                                        "<div class=\"cbp-l-caption-desc\">" +
                                            "<div class=\"btn btn-circle red btn-sm div-as-button\" style=\"margin-top: -7px; float: right;\" data-id=\"" + element["id"] + "\"><i class=\"icon-trash\"></i> Remove</div>" +
                                        "</div>" +
                                    "</div>" +
                                "</div>" +
                            "</div>" +
                        "</a>" +
                    "</div>";
                });
                content += "</div>";
                return content;
            }

            $('.div-as-button').click(buttonCallback);
            function buttonCallback(e){
                if(confirm("Do you really want to delete this image?")){
                    $.ajax({
                        url: "<%= admin_dashboard_ajax_delete_media_from_profile_path %>",
                        method: "post",
                        data: { media_id: $(this).data("id"), user_id: "<%= params[:id] %>" },
                        success: function(e){
                            if(e.media.length != 0){
                                $('.portfolio-4').html(constructNewGallery(e));

                                $('#js-grid-full-width').cubeportfolio({
                                    filters: '#js-filters-full-width',
                                    loadMore: '#js-loadMore-full-width',
                                    loadMoreAction: 'auto',
                                    layoutMode: 'mosaic',
                                    sortToPreventGaps: true,
                                    defaultFilter: '*',
                                    animationType: 'fadeOutTop',
                                    gapHorizontal: 0,
                                    gapVertical: 0,
                                    gridAdjustment: 'responsive',
                                    mediaQueries: [{
                                        width: 1500,
                                        cols: 5
                                    }, {
                                        width: 1100,
                                        cols: 4
                                    }, {
                                        width: 800,
                                        cols: 3
                                    }, {
                                        width: 480,
                                        cols: 2
                                    }, {
                                        width: 320,
                                        cols: 1
                                    }],
                                    caption: 'zoom',
                                    displayType: 'lazyLoading',
                                    displayTypeSpeed: 100,
                                    
                                    lightboxDelegate: '.cbp-lightbox',
                                    lightboxGallery: true,
                                    lightboxTitleSrc: 'data-title',
                                    lightboxCounter: '<div class="cbp-popup-lightbox-counter">{{current}} of {{total}}</div>',
                                });

                                $('.div-as-button').click(buttonCallback);
                            }else{
                                $('.cbp').html("<h3 align=\"center\">EMPTY</h3>");
                            }
                        }
                    });
                }
                return false;
            }
        });
    </script>
<% end %>

gospeltribes-webservice/app/views/admin/pages/sample_page_for_testing.html.erb
<div class="col-md-12 col-sm-12">
    <div class="portlet light ">
        <div class="portlet-title">
            <div class="caption caption-md">
                <i class="icon-bar-chart font-dark hide"></i>
                <span class="caption-subject font-green-steel bold uppercase">Members</span>
            </div>
        </div>
        <div class="portlet-body">
            <div class="table-scrollable table-scrollable-borderless">
                <select class="js-data-example-ajax" style="width: 30%;"></select>
            </div>
        </div>
    </div>
</div>
<%= content_for(:javascript) do %>
    <!--  -->
    <!-- assets/global/plugins/angularjs/plugins/ui-select/select.min.js -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('.js-data-example-ajax').select2({
              ajax: {
                url: "http://api.gospeltribes.com/smalladmin/1/ajax_for_sample_page", 
                method: "post",
                data: function(params){
                    var query = { search: params.term }
                    return query;
                },
                processResults: function (data) {
                  var results = new Array();
                  if(data != null){
                    data.predictions.forEach(function(element){
                        results.push({ "id": element["description"], "text": element["description"] });
                    });
                  }
                  return { "results": results };
                },
                minimumInputLength: 1
              }
            });
        });
    </script>
<% end %>